DROP TABLE IF EXISTS leagues CASCADE;
CREATE TABLE leagues (
  id SERIAL PRIMARY KEY NOT NULL,
  sport_type_id INTEGER REFERENCES sport_types(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  year VARCHAR(255),
  logo VARCHAR(255),
  cover_photo VARCHAR(255)
);